name: blog-islands

services:

  web:
    build: .
    ports:
      - "8000"
    environment:
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: blog
    volumes:
      - ${PROJECT_DIR}/../../public/images:/app/dist/client/images
    depends_on:
      db:
        condition: service_healthy

  db:
    build: ../../db
    image: pharus_postgres
